"""add file_hash and unique constraint to document_versions

Revision ID: 7781893645ae
Revises: c537913e013b
Create Date: 2026-06-28 12:29:22.246248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7781893645ae'
down_revision: Union[str, None] = 'c537913e013b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_document_version_number', ['document_id', 'version_number'])

    with op.batch_alter_table('user_companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_holdings'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_companies', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_holdings'), ['user_id', 'company_id'])

    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_version_number', type_='unique')

    # ### end Alembic commands ###
