"""add_holding_generation_fields

Revision ID: e5b1a2c3d4f5
Revises: f30fb431faf3
Create Date: 2026-06-20 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b1a2c3d4f5'
down_revision: Union[str, None] = 'f30fb431faf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('document_structure', sa.JSON(), nullable=True))
    op.add_column('holdings', sa.Column('style_settings', sa.JSON(), nullable=True))
    op.add_column('holdings', sa.Column('use_gost', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'use_gost')
    op.drop_column('holdings', 'style_settings')
    op.drop_column('holdings', 'document_structure')
    # ### end Alembic commands ###
